name: Update Matches

on:
 # schedule:
    # بداية اليوم (أمس + اليوم + الغد)
   # - cron: "5 0 * * *"

    # تحديث اللايف كل 5 دقائق
#    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Run updateMatches
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node updateMatches.js

